*----------------------------------------------------------------------
* SPICE Netlist Generated by TDK Corporation
* Copyright(C) 2022 TDK Corporation.
* All Rights Reserved.
*----------------------------------------------------------------------
* TDK P/N: CGA5L1X7R1H106K160AC (Multilayer Ceramic Chip Capacitor)
* Property: C=10uF
* Size(LxWxT): 3.2x1.6x1.6mm
* Model Type: Precise Model
* Model Generated on June 16, 2022
*----------------------------------------------------------------------
* Terms and conditions regarding TDK Simulation Models:
* 1)This simulation model is being provided solely for informational
*   purposes. Please refer to the specifications of the products in
*   terms of detailed characteristics of such products.
* 2)In no event shall TDK Corporation of any of its subsidiaries be
*   liable for any loss or damage arising, directly or indirectly,
*   from any information contained in this simulation model, including,
*   but not limited to loss or damages arising from any inaccuracies,
*   omissions or errors in connection with such information.
* 3)Any and all copyrights on this simulation model are owned by
*   TDK Corporation.  Duplication or redistribution of this simulation
*   model without prior written permission from TDK Corporation
*   is prohibited.
* 4)This simulation model is subject to any modification or change
*   without any prior notice.
* 5)Neither TDK Corporation nor any of its subsidiaries shall make any
*   warranty, express or implied, including but not limited to the
*   correctness, implied warranties of merchantability and fitness for
*   a particular purpose with respect to this simulation models.
* 6)The use of this simulation model shall be deemed to have consented
*   to the terms and conditions hereof.
*----------------------------------------------------------------------
* External Node Assignments:
*
*  n1 ---| |--- n2
*
*----------------------------------------------------------------------
* Applicable Conditions:
*   Temperature = 25 degC
*   DC Bias Voltage = 0 V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT CGA5L1X7R1H106K160AC_p n1 n2
C1 n1 11 9.52429487E-06
C2 n1 12 1.15159657E-07
C3 n1 13 1.15159657E-07
C4 n1 14 1.15159657E-07
C5 n1 15 1.15159657E-07
C6 n1 16 1.15159657E-07
C7 n1 17 1.15159657E-07
L1 n2 21 7.50000000E-10
R1 11 21 2.20400000E-03
R2 11 12 1.30531029E+01
R3 11 13 8.43347070E+01
R4 11 14 5.44726342E+02
R5 11 15 3.51748832E+03
R6 11 16 2.27076345E+04
R7 11 17 1.46554336E+05
R8 n1 11 5.00000000E+07
.ENDS CGA5L1X7R1H106K160AC_p
*----------------------------------------------------------------------
